import type { Metadata } from "next";
import "./globals.css";
import RouteTransition from "@/components/RouteTransition";

export const metadata: Metadata = {
  title: "K27 Animated Website",
  description: "Generated by Sourav Debnath",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RouteTransition />
        {children}
      </body>
    </html>
  );
}
